import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import "ress";
import * as layouts from "@/app/components/layouts/Index"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YOCCI_ii7 BLOG by Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <layouts.Header />
        <layouts.Sidebar />
        <layouts.Footer />
        {children}
        </body>
    </html>
  );
}
